### PR TITLE
Cassandra 4 upgrade

### PR DESCRIPTION
**Pull request by mbbs**

### CODE REVIEW

**Comment by natalie-zamani** [comment]
Thanks @mbbs! I'll re-review this over the next few days.

Just to add some context, the plan here will be to upgrade the library to a new major version, and maintain the `3.x` Datastax client version of this lib on the branch `release/1.x`

**Comment by natalie-zamani** [comment]
@joschi  Hey Jochen! It looks like the java 11 build of this repo is failing on this SonarQube analysis error:

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project dropwizard-cassandra: You're not authorized to run analysis. Please contact the project administrator. -> [Help 1]
```

Any idea what we can do to fix this? Do we need new credentials for this project?

**Comment by joschi** [comment]
@mbbs @natalie-zamani Sorry for the inconvenience!

The analysis with SonarCloud shouldn't be run for PRs originating from foreign repositories such as this one because the `SONAR_TOKEN` secret won't be available there.

I've committed https://github.com/dropwizard/dropwizard-cassandra/commit/14002eac56053e45b1c5a847c4966579207b46cd to `master`, so if you merge the latest `master` branch into this PR, it should skip the analysis with SonarCloud.

**Comment by natalie-zamani** [comment]
Thanks @joschi!

**Comment by mbbs** [comment]
Thanks @joschi

**Review by natalie-zamani — APPROVED** [review]
Thanks again for taking the time to do this @mbbs! This all looks good to me, but granted I've not used the v4 DataStax java driver personally. Let's merge this, and test out a SNAPSHOT artifact before we proceed to releasing `2.0.0`

**Pull request merged**
